In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_parquet('')

In [4]:
df.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,runtimeMinutes,nconst,category,job,...,genre_Reality-TV,genre_Romance,genre_Sci-Fi,genre_Short,genre_Sport,genre_Talk-Show,genre_Thriller,genre_War,genre_Western,genres
0,tt0011801,movie,Tötet nicht mehr,Tötet nicht mehr,0,2019,97.684611,nm0459029;nm0681726;nm0692612;nm0726256;nm0776...,actor;actor;actress;actor;actor;writer;cinemat...,\N;\N;\N;\N;\N;\N;\N;\N;\N;\N,...,0,0,0,0,0,0,0,0,0,Action;Crime
1,tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0,2021,94.000000,nm0412842;nm0895048;nm13054604,director;director;producer,\N;\N;producer,...,0,0,0,0,0,0,0,0,0,Documentary
2,tt0062336,movie,The Tango of the Widower and Its Distorting Mi...,El tango del viudo y su espejo deformante,0,2020,70.000000,nm0093680;nm0815612;nm1860495;nm0016013;nm0739...,cinematographer;actor;actress;actor;actress;di...,\N;\N;\N;\N;\N;original director;completion di...,...,0,0,0,0,0,0,0,0,0,Drama
3,tt0069049,movie,The Other Side of the Wind,The Other Side of the Wind,0,2018,122.000000,nm0613657;nm0001379;nm0462648;nm0000953;nm0001...,editor;actor;actress;actor;actress;director;pr...,\N;\N;\N;\N;\N;\N;producer;producer;\N;\N,...,0,0,0,0,0,0,0,0,0,Drama
4,tt0077684,movie,Histórias de Combóios em Portugal,Histórias de Combóios em Portugal,0,2022,46.000000,nm0127908,director,NIL,...,0,0,0,0,0,0,0,0,0,Documentary

In [12]:

genre_cols = [col.replace("genre_",'') for col in df.columns if col.startswith('genre_')]



selector = pd.DataFrame({
    "genre":genre_cols,
    "genre_selection":[True if genre=="Action" else False for genre in genre_cols]
})


selector['genre'] = genre_cols
# edited_selector = st.data_editor(selector,\
#                                 column_config = {

#     "genre":st.column_config.Column(
#         label="Genre"

#     ),
#     "genre_selection": st.column_config.CheckboxColumn(
#     label="Select Genre",
#     help = "Click on the checkbox to select the genre to be included in the visualization below",
#     width="small",
#     default=False
#     )   
# },
#     disabled = ["genre"],
#     hide_index=True)

cols_selected = selector.loc[selector['genre_selection']==True]['genre'].tolist()

# st.session_state.cols_selected = cols_selected #Saves columns selected as a list type

genres_of_interest = ["genre_Action", "genre_Romance"]

display_df = pd.DataFrame({"startYear":[num for num in range(2014,2024)]})



for genre in genres_of_interest:
    gb = df.groupby(['startYear',genre])
    means = gb['popularity_score'].mean().reset_index()
    means.rename(columns={'popularity_score':f"{genre.replace('genre_','')}"}, inplace=True)
    means = means[means[genre]==1].set_index('startYear').drop(genre,axis=1)
    display_df = display_df.merge(means, how='right',left_index=True, right_index=True)

display_df.index = display_df.index.astype('string')

if 'startYear' in display_df.columns:
    display_df.drop('startYear',axis=1,inplace=True)

display_df.reset_index(inplace=True)

df_melted = display_df.melt(id_vars='startYear', var_name='genre', value_name='popularity_score')

In [13]:
df_melted

   startYear    genre  popularity_score
0       2014   Action          6.135045
1       2015   Action          6.125219
2       2016   Action          6.125759
3       2017   Action          6.142022
4       2018   Action          6.130501
5       2019   Action          6.144402
6       2020   Action          6.110978
7       2021   Action          6.138827
8       2022   Action          6.185080
9       2023   Action          6.277651
10      2014  Romance          6.248880
11      2015  Romance          6.275831
12      2016  Romance          6.256667
13      2017  Romance          6.235737
14      2018  Romance          6.254570
15      2019  Romance          6.264243
16      2020  Romance          6.274888
17      2021  Romance          6.277575
18      2022  Romance          6.292629
19      2023  Romance          6.290292